/*
# Device Pairing Requests Table

## Purpose
Stores device pairing requests for the kiosk/tablet registration flow.
A device generates an 8-character code, sends a pairing request, and an admin
generates a confirmation code. The device enters the confirmation code to complete
registration and save the device.

## Flow
1. Device opens pairing modal → generates 8-char `device_code` (valid 5 min)
2. Device clicks "Registrar" → inserts a row with status = 'pending'
3. Admin sees the request in "Solicitudes" tab → generates 8-char `confirm_code`
4. Device enters `confirm_code` → status becomes 'confirmed' → device is saved

## New Tables
- `device_pairing_requests`
  - `id` (uuid, PK)
  - `device_key` (text) — the unique device identifier from localStorage
  - `device_code` (text, 8 chars) — code shown on the device, valid 5 min
  - `confirm_code` (text, 8 chars, nullable) — code generated by admin
  - `site_name` (text, nullable) — optional name for the kiosk location
  - `device_info` (text, nullable) — browser/OS info
  - `status` (text) — 'pending' | 'confirmed' | 'expired' | 'rejected'
  - `expires_at` (timestamptz) — when the device_code expires (5 min from creation)
  - `confirmed_at` (timestamptz, nullable) — when the admin confirmed
  - `created_at` (timestamptz)

## Security
- RLS enabled
- anon + authenticated can INSERT (devices create their own requests)
- anon + authenticated can SELECT (admin panel needs to see requests)
- authenticated can UPDATE (admin generates confirm_code)
- authenticated can DELETE (admin can reject/remove requests)
*/

CREATE TABLE IF NOT EXISTS device_pairing_requests (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  device_key    text NOT NULL,
  device_code   text NOT NULL,
  confirm_code  text,
  site_name     text,
  device_info   text,
  status        text NOT NULL DEFAULT 'pending',
  expires_at    timestamptz NOT NULL DEFAULT (now() + interval '5 minutes'),
  confirmed_at  timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE device_pairing_requests ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_select_pairing_requests" ON device_pairing_requests;
CREATE POLICY "anon_select_pairing_requests"
  ON device_pairing_requests FOR SELECT
  TO anon, authenticated USING (true);

DROP POLICY IF EXISTS "anon_insert_pairing_requests" ON device_pairing_requests;
CREATE POLICY "anon_insert_pairing_requests"
  ON device_pairing_requests FOR INSERT
  TO anon, authenticated WITH CHECK (true);

DROP POLICY IF EXISTS "auth_update_pairing_requests" ON device_pairing_requests;
CREATE POLICY "auth_update_pairing_requests"
  ON device_pairing_requests FOR UPDATE
  TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "auth_delete_pairing_requests" ON device_pairing_requests;
CREATE POLICY "auth_delete_pairing_requests"
  ON device_pairing_requests FOR DELETE
  TO anon, authenticated USING (true);

-- Index for looking up pending requests
CREATE INDEX IF NOT EXISTS idx_pairing_status ON device_pairing_requests (status);
CREATE INDEX IF NOT EXISTS idx_pairing_device_key ON device_pairing_requests (device_key);